#!/usr/bin/env bash
# This code prints Best School 10 times and "Hi" immediately after the 9th"
i=i
while [ "$i" -le 10]
        do
                echo "Best School"
                if ["$i" -eq 9 ]; then
                        echo "Hi"
                fi
                (( i++ ))
done
